###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID vlsi.iitgn.ac.in)
#  Generated on:      Tue Apr 14 18:08:03 2026
#  Design:            microprocessor_pad_top
#  Command:           create_ccopt_clock_tree_spec -file /home/thoshith/work_risc_v/scl6m/cts/run/microprocessor_pad_top_ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins were identified as implicit sinks
# The following pins are design outputs carrying SDC clocks
# These pins are ignore skew pins
set_ccopt_property sink_type -pin CLKOUT_pad ignore
set_ccopt_property sink_type_reasons -pin CLKOUT_pad {implicit design_io}

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk_pad true

# Clocks present at pin clk_pad
#   clk_pad (period 20.000ns) in timing_config functional([/home/thoshith/work_risc_v/scl6m/floorplanning/microprocessor_pad_top_placement.enc.dat/mmmc/modes/functional/functional.sdc])
create_ccopt_clock_tree -name clk_pad -source clk_pad -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -early -clock_tree clk_pad 2.500
set_ccopt_property target_max_trans_sdc -delay_corner max_delay -late -clock_tree clk_pad 4.000
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner max_delay -early -rise -clock_tree clk_pad 0.800
set_ccopt_property source_latency -delay_corner max_delay -early -fall -clock_tree clk_pad 0.800
set_ccopt_property source_latency -delay_corner max_delay -late -rise -clock_tree clk_pad 2.000
set_ccopt_property source_latency -delay_corner max_delay -late -fall -clock_tree clk_pad 2.000
set_ccopt_property source_latency -delay_corner min_delay -early -rise -clock_tree clk_pad 0.800
set_ccopt_property source_latency -delay_corner min_delay -early -fall -clock_tree clk_pad 0.800
set_ccopt_property source_latency -delay_corner min_delay -late -rise -clock_tree clk_pad 2.000
set_ccopt_property source_latency -delay_corner min_delay -late -fall -clock_tree clk_pad 2.000
# Clock period setting for source pin of clk_pad
set_ccopt_property clock_period -pin clk_pad 20

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk_pad in timing_config:functional (sdc /home/thoshith/work_risc_v/scl6m/floorplanning/microprocessor_pad_top_placement.enc.dat/mmmc/modes/functional/functional.sdc)
create_ccopt_skew_group -name clk_pad/functional -sources clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_pad/functional true
set_ccopt_property extracted_from_clock_name -skew_group clk_pad/functional clk_pad
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_pad/functional functional
set_ccopt_property extracted_from_delay_corners -skew_group clk_pad/functional {max_delay min_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

