tclmode

# Generated by Genus(TM) Synthesis Solution 21.19-s055_1, revision 1.568
# Generated on: Tue Apr 14 17:04:43 IST 2026 (Tue Apr 14 11:34:43 UTC 2026)

set_screen_display -noprogress
set_dofile_abort exit

### Alias mapping flow is enabled. ###
# Root attribute 'alias_flow'                 was 'true'.

set lec_version [regsub {(-)[A-Za-z]} $env(LEC_VERSION) ""]

# Turns on the flowgraph datapath solver.
set wlec_analyze_dp_flowgraph true
# Indicates that resource sharing datapath optimization is present.
set share_dp_analysis         true

# The flowgraph solver is recommended for datapath analysis in LEC 19.1 or newer.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required &&
    $wlec_analyze_dp_flowgraph} {
    set DATAPATH_SOLVER_OPTION "-flowgraph"
} elseif {$share_dp_analysis} {
    set DATAPATH_SOLVER_OPTION "-share"
} else {
    set DATAPATH_SOLVER_OPTION ""
}

tcl_set_command_name_echo on

set logfile ./logs/rtl2intermediate.lec.log ;# user can modify this name for succeeding runs

set_log_file $logfile -replace

usage -auto -elapse

set_mapping_method -sensitive

set_verification_information rtl_fv_map_db

read_implementation_information fv/microprocessor_pad_top -revised fv_map

# Root attribute 'wlec_multithread_license_list' can be used to specify a license list
# for multithreaded processing. The default list is used otherwise.
set_parallel_option -threads 1,4 -norelease_license
set_compare_options -threads 1,4

set env(RC_VERSION)     "21.19-s055_1"
set env(CDN_SYNTH_ROOT) "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86"
set CDN_SYNTH_ROOT      "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86"
set env(CW_DIR) "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware"
set CW_DIR      "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware"
set lec_version_required "21.20249"
if { ($lec_version < $lec_version_required) &&
    [file exists /opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware/old_encrypt_sim]} {
    set env(CW_DIR_SIM) "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware/old_encrypt_sim"
    set CW_DIR_SIM      "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware/old_encrypt_sim"
} else {
    set env(CW_DIR_SIM) "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware/sim"
    set CW_DIR_SIM      "/opt/tools/Cadence/Cadence_tools/GENUS/tools.lnx86/lib/chipware/sim"
}
set_multiplier_implementation boothrca -both

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

# ILM modules: 

add_search_path /opt/tools/Cadence/Cadence_lib/scl_pdk_v3/SCLPDK_V3.0_KIT/scl180/stdcell/fs120/6M1L/liberty/lib_flow_ff /opt/tools/Cadence/Cadence_lib/scl_pdk_v3/SCLPDK_V3.0_KIT/scl180/stdcell/fs120/6M1L/liberty/lib_flow_ss -library -both
read_library -liberty -both \
    /opt/tools/Cadence/Cadence_lib/scl_pdk_v3/SCLPDK_V3.0_KIT/scl180/stdcell/fs120/6M1L/liberty/lib_flow_ss/tsl18fs120_scl_ss.lib \
    /opt/tools/Cadence/Cadence_lib/scl_pdk_v3/SCLPDK_V3.0_KIT/scl180/iopad/cio150/6M1L/liberty/tsl18cio150_max.lib \
    /opt/tools/Cadence/Cadence_lib/scl_pdk_v3/SCLPDK_V3.0_KIT/scl180/stdcell/fs120/6M1L/liberty/lib_flow_ss/tsl18fs120_scl_ss.lib \
    /opt/tools/Cadence/Cadence_lib/scl_pdk_v3/SCLPDK_V3.0_KIT/scl180/iopad/cio150/6M1L/liberty/tsl18cio150_max.lib

set_undriven_signal 0 -golden
set lec_version_required "16.20100"
if {$lec_version >= $lec_version_required} {
    set_naming_style genus -golden
} else {
    set_naming_style rc -golden
}
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden
set lec_version_required "17.10200"
if {$lec_version >= $lec_version_required} {
    set_naming_rule -ungroup_separator {_} -golden
}

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue.
# This option is only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -unsigned_conversion_overflow on
set_hdl_option -v_to_vd on

set lec_version_required "20.20226"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -VERILOG_INCLUDE_DIR "sep:src"
} else {
    set_hdl_options -VERILOG_INCLUDE_DIR "sep:src:cwd"
}
delete_search_path -all -design -golden
add_search_path /home/thoshith/work_risc_v/scl6m/design -design -golden
read_design -enumconstraint -define SYNTHESIS  -merge bbox -golden -lastmod -noelab  -sv09 /home/thoshith/work_risc_v/scl6m/design/Write_back.v /home/thoshith/work_risc_v/scl6m/design/wrapper_memory.v /home/thoshith/work_risc_v/scl6m/design/type_decoder.v /home/thoshith/work_risc_v/scl6m/design/register_file.v /home/thoshith/work_risc_v/scl6m/design/program_counter.v /home/thoshith/work_risc_v/scl6m/design/mux2_4.v /home/thoshith/work_risc_v/scl6m/design/mux1_2.v /home/thoshith/work_risc_v/scl6m/design/microprocessor_pad_top.v /home/thoshith/work_risc_v/scl6m/design/Microprocessor.v /home/thoshith/work_risc_v/scl6m/design/memstage_pipe.v /home/thoshith/work_risc_v/scl6m/design/memory_stage.v /home/thoshith/work_risc_v/scl6m/design/instruc_mem_top.v /home/thoshith/work_risc_v/scl6m/design/instruction_memory.v /home/thoshith/work_risc_v/scl6m/design/immediate_gen.v /home/thoshith/work_risc_v/scl6m/design/fetch_pipe.v /home/thoshith/work_risc_v/scl6m/design/Fetch.v /home/thoshith/work_risc_v/scl6m/design/execute_pipe.v /home/thoshith/work_risc_v/scl6m/design/execute_forwarding.v /home/thoshith/work_risc_v/scl6m/design/Execute.v /home/thoshith/work_risc_v/scl6m/design/decode_pipe.v /home/thoshith/work_risc_v/scl6m/design/Decode.v /home/thoshith/work_risc_v/scl6m/design/data_memory_top.v /home/thoshith/work_risc_v/scl6m/design/data_memory.v /home/thoshith/work_risc_v/scl6m/design/Core.v /home/thoshith/work_risc_v/scl6m/design/control_unit.v /home/thoshith/work_risc_v/scl6m/design/control_decoder.v /home/thoshith/work_risc_v/scl6m/design/branch.v /home/thoshith/work_risc_v/scl6m/design/alu.v /home/thoshith/work_risc_v/scl6m/design/adder.v
elaborate_design -golden -root {microprocessor_pad_top} -rootonly 

read_design -verilog95   -revised -lastmod -noelab fv/microprocessor_pad_top/fv_map.v.gz
elaborate_design -revised -root {microprocessor_pad_top}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

set_flatten_model -balanced_modeling

#add_name_alias fv/microprocessor_pad_top/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff dlat -both

# modules were tagged with 'unresolved' attribute during synthesis
#   can cause non-equivalences if ports in Golden and Revised do not match
# attribute write_vlog_empty_module_for_black_box is set to false in synthesis
#   can cause non-equivalences since port directions will be inferred
add_black_box pfrelr -golden

# Reports the quality of the implementation information.
# This command is only available with LEC 20.10-p100 or later.
set lec_version_required "20.10100"
if {$lec_version >= $lec_version_required} {
    check_verification_information
}

set_analyze_option -auto -report_map

write_hier_compare_dofile hier_tmp3.lec.do -verbose -noexact_pin_match -constraint -usage \
-replace -balanced_extraction -input_output_pin_equivalence \
-prepend_string "report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath $DATAPATH_SOLVER_OPTION -verbose"
run_hier_compare hier_tmp3.lec.do -dynamic_hierarchy

report_hier_compare_result -dynamicflattened

report_verification -hier -verbose

set_system_mode lec
write_compared_points noneq.compared_points.microprocessor_pad_top.rtl.fv_map.tcl -class noneq -tclmode -replace
set lec_version_required "21.10100"
if {$lec_version >= $lec_version_required} {
    analyze_nonequivalent -source_diagnosis
    report_nonequivalent_analysis > noneq.source_diag.microprocessor_pad_top.rtl.fv_map.rpt
}
report_test_vector -noneq > noneq.test_vector.microprocessor_pad_top.rtl.fv_map.rpt
set_system_mode setup
write_verification_information
report_verification_information

# Reports how effective the implementation information was.
# This command is only available with LEC 18.20-d330 or later.
set lec_version_required "18.20330"
if {$lec_version >= $lec_version_required} {
    report_implementation_information
}

set_system_mode lec

puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}

# Generate a detailed summary of the run.
# This command is available with LEC 19.10-p100 or later.
set lec_version_required "19.10100"
if {$lec_version >= $lec_version_required} {
    analyze_results -logfiles $logfile
}

vpxmode

exit -f
